version: "3"
services:
  drone-server:
    image: drone/drone:latest
    ports:
      - 80:80
      - 443:443
    restart: always
    environment:
      - DRONE_SERVER_PROTO=http
      - DRONE_SERVER_HOST=${DRONE_SERVER_HOST}
      - DRONE_RPC_SECRET=${DRONE_RPC_SECRET}
      - DRONE_GITHUB_SERVER=https://github.com
      - DRONE_GITHUB_CLIENT_ID=${DRONE_GITHUB_CLIENT_ID}
      - DRONE_GITHUB_CLIENT_SECRET=${DRONE_GITHUB_CLIENT_SECRET}
      - DRONE_USER_CREATE=username:fenglinchang996,admin:true
    volumes:
      - /var/lib/drone:/data
